<?php

/**
 * @file
 * Contains configuration_managment_test.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function configuration_managment_test_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the configuration_managment_test module.
    case 'help.page.configuration_managment_test':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Demo module for testing config managment') . '</p>';
      return $output;

    default:
  }
}
