<?php

namespace Drupal\test\Controller;
use Drupal\Core\Controller\ControllerBase;

use Drupal\test\Services\testService;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\Response;

class TestController extends ControllerBase {

  public function test($num) {

    $test_service_obj = new testService();
    $string_test  = $test_service_obj->getTest($num);

    return new Response($string_test);
  }


  public static function create(ContainerInterface $container)
  {
    return parent::create($container); // TODO: Change the autogenerated stub
  }
}