<?php

/**
 * @file
 * Contains test_block_example.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function test_block_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the test_block_example module.
    case 'help.page.test_block_example':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
